# yamllint disable rule:truthy
# yamllint disable rule:indentation
name: build image

on:
  pull_request:
    branches: main
  push:
    branches: main
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DragonCrafted87-Turtle-Plated-Helmets
        path: |
          data/*
          pack.mcmeta
          LICENSE
